server:
  servlet:
    context-path: /jason
  port: 8087
  tomcat:
    uri-encoding: utf-8
logging:
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: dev
swagger:
  is:
    show: true
  #实体扫描，多个package用逗号或者分号分隔

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  typeAliasesPackage: com.jason.jason_start.domain.*
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl